language: python
python:
  - "2.7"
  - "3.3"
# command to install dependencies
install: 
  - "pip install -r requirements.txt"
  - "pip install -r requirements-test.txt"
  - "pip install python-coveralls"
# command to run tests
script: 
  - "python setup.py test"
after_success:
  - "coveralls"
notifications:
  irc:
    channels:
      - "chat.freenode.net#icspy"
    use_notice: false
    skip_join: true
    template:
      - "build#%{build_number} (%{branch} - %{commit}): %{message}"
      - "%{build_url}"